# 🪰 Fly.io - Deploy Configuration
app = "vidashield"
primary_region = "gru"  # São Paulo, Brasil

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  NODE_ENV = "production"
  # Adicionar via: fly secrets set VITE_SUPABASE_URL=https://...
  # fly secrets set VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiI...
  # fly secrets set VITE_HCAPTCHA_SITE_KEY=866663ec-b850-4a54-8884-8376d11051c4

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s" 